---

- name: etckeeper test
  etckeeper_check:

- name: Install apt key for java
  apt_key:
    keyserver: keyserver.ubuntu.com
    id: C2518248EEA14886
    state: present

- name: Add java repo
  apt_repository:
    repo: "deb http://ppa.launchpad.net/webupd8team/java/ubuntu {{ ansible_distribution_release }} main"
    state: present

- name: Accept oracle license
  debconf:
    name: oracle-java8-installer
    question: shared/accepted-oracle-license-v1-1
    value: 'true'
    vtype: select

- name: Install packages
  apt:
    name:
    - java-package
    - java-common
    - oracle-java8-installer
    state: present
    update_cache: yes
    cache_valid_time: "{{ apt_cache_valid_time|default(86400) }}"  # 24h

- name: Create a group for tomcat
  group:
    name: tomcat
    state: present

- name: Add a user for tomcat
  user:
    create_home: yes
    group: tomcat
    home: /opt/tomcat
    name: tomcat
    shell: /bin/false
    state: present

- name: Download and unarchive tomcat
  unarchive:
    dest: /opt/tomcat
    extra_opts:
      - --strip-components=1
    remote_src: yes
    src: http://mirror.23media.de/apache/tomcat/tomcat-9/v9.0.14/bin/apache-tomcat-9.0.14.tar.gz

- name: Set permissions for tomcat directory
  file:
    group: tomcat
    owner: tomcat
    path: /opt/tomcat
    recurse: yes
    state: directory

- name: Add JAVA_HOME and PATH variables to /etc/profile file
  blockinfile:
    block: |
      JAVA_HOME={{ java_home }}
      PATH=${PATH}:{{ java_home }}/bin
    insertafter: EOF
    marker: "#-- {mark} ANSIBLE MANAGED BLOCK for java8-tomcat role --"
    path: /etc/profile

- name: Deploy tomcat service file
  template:
    src: tomcat.service.j2
    dest: /etc/systemd/system/tomcat.service

- name: Start tomcat service
  systemd:
    daemon_reload: yes
    name: tomcat
    state: started

- name: etckeeper post task
  etckeeper:
    msg: autocommit after ansible-role-java8-tomcat

...
